// Auto-generated railcard price data
// Last updated: 2025-12-05T03:16:21.392336
// DO NOT EDIT MANUALLY - This file is generated by the scraper

const railcardData = [
  {
    "name": "Carte Avantage Jeune",
    "description": "Pour les 12-27 ans",
    "prices": [
      {
        "retailer": "SNCF Connect",
        "price": 49.0,
        "url": "https://www.sncf-connect.com/catalogue/description/carte-avantage-jeune",
        "promo": false,
        "available": true,
        "error": "403 Client Error: Forbidden for url: https://www.sncf-connect.com/catalogue/description/carte-avantage-jeune",
        "timestamp": "2025-12-05T03:16:16.271866"
      },
      {
        "retailer": "Trainline",
        "price": 9.0,
        "url": "https://www.thetrainline.com/fr/compagnies-ferroviaires/sncf/cartes-abonnements-de-train",
        "promo": true,
        "available": true,
        "note": "Promotion en cours",
        "timestamp": "2025-12-05T03:16:21.383685"
      },
      {
        "retailer": "Régions (TER)",
        "price": null,
        "url": null,
        "promo": false,
        "available": false,
        "note": "Varie selon région",
        "timestamp": "2025-12-05T03:16:21.392326"
      }
    ]
  },
  {
    "name": "Carte Avantage Adulte",
    "description": "Pour les 27-59 ans",
    "prices": [
      {
        "retailer": "SNCF Connect",
        "price": 49.0,
        "url": "https://www.sncf-connect.com/catalogue/description/carte-avantage-adulte",
        "promo": false,
        "available": true,
        "timestamp": "2025-12-05T03:16:17.530044"
      },
      {
        "retailer": "Trainline",
        "price": 9.0,
        "url": "https://www.thetrainline.com/fr/compagnies-ferroviaires/sncf/cartes-abonnements-de-train",
        "promo": true,
        "available": true,
        "note": "Promotion en cours",
        "timestamp": "2025-12-05T03:16:21.387655"
      },
      {
        "retailer": "Régions (TER)",
        "price": null,
        "url": null,
        "promo": false,
        "available": false,
        "note": "Varie selon région",
        "timestamp": "2025-12-05T03:16:21.392329"
      }
    ]
  },
  {
    "name": "Carte Avantage Senior",
    "description": "Pour les 60 ans et plus",
    "prices": [
      {
        "retailer": "SNCF Connect",
        "price": 49.0,
        "url": "https://www.sncf-connect.com/catalogue/description/carte-avantage-senior",
        "promo": false,
        "available": true,
        "error": "403 Client Error: Forbidden for url: https://www.sncf-connect.com/catalogue/description/carte-avantage-senior",
        "timestamp": "2025-12-05T03:16:18.746405"
      },
      {
        "retailer": "Trainline",
        "price": 9.0,
        "url": "https://www.thetrainline.com/fr/compagnies-ferroviaires/sncf/cartes-abonnements-de-train",
        "promo": true,
        "available": true,
        "note": "Promotion en cours",
        "timestamp": "2025-12-05T03:16:21.391618"
      },
      {
        "retailer": "Régions (TER)",
        "price": null,
        "url": null,
        "promo": false,
        "available": false,
        "note": "Varie selon région",
        "timestamp": "2025-12-05T03:16:21.392331"
      }
    ]
  }
];

const lastUpdate = '2025-12-05T03:16:21.392336';

// Export for use in HTML
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { railcardData, lastUpdate };
}
