// Auto-generated railcard price data
// Last updated: 2026-02-11T04:27:27.876677
// DO NOT EDIT MANUALLY - This file is generated by the scraper

const railcardData = [
  {
    "name": "Carte Avantage Jeune",
    "description": "Pour les 12-27 ans",
    "prices": [
      {
        "retailer": "SNCF Connect",
        "price": 49.0,
        "url": "https://www.sncf-connect.com/catalogue/description/carte-avantage-jeune",
        "promo": false,
        "available": true,
        "error": "403 Client Error: Forbidden for url: https://www.sncf-connect.com/catalogue/description/carte-avantage-jeune",
        "timestamp": "2026-02-11T04:27:24.564218"
      },
      {
        "retailer": "Trainline",
        "price": 49.0,
        "url": "https://www.thetrainline.com/fr/compagnies-ferroviaires/sncf/cartes-abonnements-de-train",
        "promo": false,
        "available": true,
        "note": null,
        "timestamp": "2026-02-11T04:27:27.869855"
      },
      {
        "retailer": "Régions (TER)",
        "price": null,
        "url": null,
        "promo": false,
        "available": false,
        "note": "Varie selon région",
        "timestamp": "2026-02-11T04:27:27.876671"
      }
    ]
  },
  {
    "name": "Carte Avantage Adulte",
    "description": "Pour les 27-59 ans",
    "prices": [
      {
        "retailer": "SNCF Connect",
        "price": 49.0,
        "url": "https://www.sncf-connect.com/catalogue/description/carte-avantage-adulte",
        "promo": false,
        "available": true,
        "error": "403 Client Error: Forbidden for url: https://www.sncf-connect.com/catalogue/description/carte-avantage-adulte",
        "timestamp": "2026-02-11T04:27:24.752232"
      },
      {
        "retailer": "Trainline",
        "price": 49.0,
        "url": "https://www.thetrainline.com/fr/compagnies-ferroviaires/sncf/cartes-abonnements-de-train",
        "promo": false,
        "available": true,
        "note": null,
        "timestamp": "2026-02-11T04:27:27.872701"
      },
      {
        "retailer": "Régions (TER)",
        "price": null,
        "url": null,
        "promo": false,
        "available": false,
        "note": "Varie selon région",
        "timestamp": "2026-02-11T04:27:27.876674"
      }
    ]
  },
  {
    "name": "Carte Avantage Senior",
    "description": "Pour les 60 ans et plus",
    "prices": [
      {
        "retailer": "SNCF Connect",
        "price": 49.0,
        "url": "https://www.sncf-connect.com/catalogue/description/carte-avantage-senior",
        "promo": false,
        "available": true,
        "error": "403 Client Error: Forbidden for url: https://www.sncf-connect.com/catalogue/description/carte-avantage-senior",
        "timestamp": "2026-02-11T04:27:25.000434"
      },
      {
        "retailer": "Trainline",
        "price": 49.0,
        "url": "https://www.thetrainline.com/fr/compagnies-ferroviaires/sncf/cartes-abonnements-de-train",
        "promo": false,
        "available": true,
        "note": null,
        "timestamp": "2026-02-11T04:27:27.875545"
      },
      {
        "retailer": "Régions (TER)",
        "price": null,
        "url": null,
        "promo": false,
        "available": false,
        "note": "Varie selon région",
        "timestamp": "2026-02-11T04:27:27.876676"
      }
    ]
  }
];

const lastUpdate = '2026-02-11T04:27:27.876677';

// Export for use in HTML
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { railcardData, lastUpdate };
}
