// Auto-generated railcard price data
// Last updated: 2026-07-19T05:18:14.461239
// DO NOT EDIT MANUALLY - This file is generated by the scraper

const railcardData = [
  {
    "name": "Carte Avantage Jeune",
    "description": "Pour les 12-27 ans",
    "prices": [
      {
        "retailer": "SNCF Connect",
        "price": 49.0,
        "url": "https://www.sncf-connect.com/catalogue/description/carte-avantage-jeune",
        "promo": false,
        "available": true,
        "timestamp": "2026-07-19T05:18:06.867629"
      },
      {
        "retailer": "Trainline",
        "price": 10.0,
        "url": "https://www.thetrainline.com/fr/compagnies-ferroviaires/sncf/cartes-abonnements-de-train",
        "promo": true,
        "available": true,
        "note": "Promotion en cours",
        "timestamp": "2026-07-19T05:18:14.457130"
      },
      {
        "retailer": "Régions (TER)",
        "price": null,
        "url": null,
        "promo": false,
        "available": false,
        "note": "Varie selon région",
        "timestamp": "2026-07-19T05:18:14.461232"
      }
    ]
  },
  {
    "name": "Carte Avantage Adulte",
    "description": "Pour les 27-59 ans",
    "prices": [
      {
        "retailer": "SNCF Connect",
        "price": 49.0,
        "url": "https://www.sncf-connect.com/catalogue/description/carte-avantage-adulte",
        "promo": false,
        "available": true,
        "timestamp": "2026-07-19T05:18:09.101666"
      },
      {
        "retailer": "Trainline",
        "price": 10.0,
        "url": "https://www.thetrainline.com/fr/compagnies-ferroviaires/sncf/cartes-abonnements-de-train",
        "promo": true,
        "available": true,
        "note": "Promotion en cours",
        "timestamp": "2026-07-19T05:18:14.458701"
      },
      {
        "retailer": "Régions (TER)",
        "price": null,
        "url": null,
        "promo": false,
        "available": false,
        "note": "Varie selon région",
        "timestamp": "2026-07-19T05:18:14.461236"
      }
    ]
  },
  {
    "name": "Carte Avantage Senior",
    "description": "Pour les 60 ans et plus",
    "prices": [
      {
        "retailer": "SNCF Connect",
        "price": 49.0,
        "url": "https://www.sncf-connect.com/catalogue/description/carte-avantage-senior",
        "promo": false,
        "available": true,
        "timestamp": "2026-07-19T05:18:10.653371"
      },
      {
        "retailer": "Trainline",
        "price": 10.0,
        "url": "https://www.thetrainline.com/fr/compagnies-ferroviaires/sncf/cartes-abonnements-de-train",
        "promo": true,
        "available": true,
        "note": "Promotion en cours",
        "timestamp": "2026-07-19T05:18:14.460258"
      },
      {
        "retailer": "Régions (TER)",
        "price": null,
        "url": null,
        "promo": false,
        "available": false,
        "note": "Varie selon région",
        "timestamp": "2026-07-19T05:18:14.461238"
      }
    ]
  }
];

const lastUpdate = '2026-07-19T05:18:14.461239';

// Export for use in HTML
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { railcardData, lastUpdate };
}
