name: Update Railcard Prices

on:
  schedule:
    # Tous les jours à 2h du matin (heure UTC)
    - cron: '0 2 * * *'
  workflow_dispatch: # Permet de lancer manuellement

# Donner les permissions d'écriture
permissions:
  contents: write

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
    
    - name: Run scraper
      run: |
        python scraper.py
    
    - name: Check for changes
      id: check_changes
      run: |
        if [[ -n $(git status -s) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add railcard_data.js railcard_prices.json
        git commit -m "🤖 Auto-update prices $(date '+%Y-%m-%d %H:%M')"
        git push
