name: Update Railcard Prices

on:
  schedule:
    # Tous les jours à 2h du matin (heure UTC)
    - cron: '0 2 * * *'
  workflow_dispatch: # Permet de lancer manuellement

# IMPORTANT: Donner les permissions nécessaires pour pusher
permissions:
  contents: write

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
    
    - name: Run scraper
      run: |
        python scraper.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add railcard_data.js railcard_prices.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-update prices $(date '+%Y-%m-%d')" && git push)
